'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
export interface MetroHeroProps {videoSrc?:string;poster?:string;title?:string;scrollHint?:string;tagline?:string;signature?:{name:string;url:string}|false;scrubDistance?:number;className?:string;style?:CSSProperties}
const DEFAULT_VIDEO='https://cdn.21st.dev/assets/mirror/21/21a77eac28eacbb7e142016eefeaa0b4a766619e51113629a3bc6df6af066c0f.mp4';
// Adapted from the supplied hero. A sticky stage scrubs through native scroll,
// then releases naturally. Never fixes body or captures wheel/touch events.
export default function MetroHero({videoSrc=DEFAULT_VIDEO,poster='assets/aryan.webp',title='From curiosity to creation.',scrollHint='SCROLL TO EXPLORE',tagline='Ideas become real when you build them.',signature=false,scrubDistance=1200,className='',style}:MetroHeroProps){
 const section=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),stage=useRef<HTMLDivElement>(null);
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[compact,setCompact]=useState(()=>matchMedia('(max-width: 760px), (prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const m=matchMedia('(max-width: 760px), (prefers-reduced-motion: reduce)');const change=()=>setCompact(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);
 useEffect(()=>{if(!ready||failed||compact)return;let frame=0;const update=()=>{frame=0;const s=section.current,v=video.current;if(!s||!v||!Number.isFinite(v.duration))return;const r=s.getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/Math.max(1,s.offsetHeight-innerHeight)));stage.current?.style.setProperty('--video-progress',String(p));if(!v.seeking&&Math.abs(v.currentTime-p*v.duration)>.05)v.currentTime=Math.min(Math.max(0,v.duration-.05),p*v.duration)};const queue=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',queue,{passive:true});window.addEventListener('resize',queue);video.current?.addEventListener('seeked',queue);queue();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',queue);window.removeEventListener('resize',queue);video.current?.removeEventListener('seeked',queue)}},[ready,failed,compact]);
 return <section ref={section} className={`metro-hero ${compact||failed||!ready?'metro-static':''} ${className}`} style={{...style,'--scrub-distance':`${Math.max(0,scrubDistance)}px`} as CSSProperties} aria-label="Creative process film"><div ref={stage} className="metro-stage"><video ref={video} src={compact?undefined:videoSrc} poster={poster} muted playsInline preload={compact?'none':'metadata'} onLoadedMetadata={()=>setReady(true)} onError={()=>setFailed(true)} aria-hidden="true"/><div className="metro-shade"/><div className="metro-top"><span>THE PROCESS / ARYAN VIRAT</span><a href="#work">Skip to projects ↗</a></div><div className="metro-copy"><span className="metro-kicker">LEARN. EXPERIMENT. BUILD.</span><h2>{title}</h2><p>{tagline}</p></div><div className="metro-bottom"><span>{compact||failed?'EXPLORE MY WORK BELOW':scrollHint+' ↓'}</span>{signature&&<a href={signature.url} target="_blank" rel="noopener noreferrer">{signature.name} ↗</a>}</div><div className="metro-progress"/></div></section>
}
