import React from 'react';
import {createRoot} from 'react-dom/client';
import ContributionSkyline from '../components/ui/contribution-skyline';
import {FullScreenScrollFX, type FXSection} from '../components/ui/full-screen-scroll-fx';
import activity from './contributions.json';
const sections:FXSection[]=[
{id:'lost-found',leftLabel:'Lost & Found',title:'Find what matters.',rightLabel:'Individual · Full-stack development',background:'assets/lost-found.webp',description:'A campus recovery platform with image uploads, rule-based matching, ownership verification, and administrative workflows.',href:'https://github.com/virat991v/lost-foundweb',live:'https://lost-found.tech'},
{id:'vaultkey',leftLabel:'VaultKey',title:'Share with confidence.',rightLabel:'Team · UI/UX & frontend development',background:'assets/vaultkey.webp',description:'Designed in Figma and built the responsive frontend for secure file sharing, uploads, dashboards, and sharing controls, collaborating with the backend team.',href:'https://github.com/virat991v/Vaultkey'},
{id:'gyansahitya',leftLabel:'GyanSahitya',title:'Give knowledge a new home.',rightLabel:'Individual · Design & development',background:'assets/gyansahitya.webp',description:'A student marketplace for selling and donating textbooks, notes, and academic resources, with authenticated listings and image uploads.',href:'https://github.com/virat991v/gyansahitya'},
{id:'air-writer',leftLabel:'Air Writer',title:'Ideas, drawn in the air.',rightLabel:'Individual · Computer vision prototype',background:'assets/air-writer.webp',description:'An online teaching prototype using MediaPipe hand tracking and gestures to draw, erase, pause, and change colours on a digital canvas.',href:'https://github.com/virat991v/hand-traker'}];
class Boundary extends React.Component<{children:React.ReactNode;fallback:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
const work=document.getElementById('scroll-fx-root');if(work)createRoot(work).render(<Boundary fallback={<p className="widget-error">Explore all four projects on <a href="https://github.com/virat991v">GitHub ↗</a>.</p>}><FullScreenScrollFX sections={sections}/></Boundary>);
const skyline=document.getElementById('skyline-root');if(skyline)createRoot(skyline).render(<Boundary fallback={<p className="widget-error">Activity chart unavailable. <a href="https://github.com/virat991v">View my GitHub profile ↗</a></p>}><ContributionSkyline data={activity.days} endDate={activity.days.at(-1)?.date} palette="ember" defaultView="3d" title="A year of building, one day at a time." footer={<>GitHub activity snapshot · Updated {new Date(activity.updatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} · <a href="https://github.com/virat991v" target="_blank" rel="noopener noreferrer">View profile ↗</a></>} /></Boundary>);
